// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB85e-ZfMehesIR5EX-v85dvJIiRoelhmU',
    appId: '1:174693600398:web:bfa93bd293928e9e758ddf',
    messagingSenderId: '174693600398',
    projectId: 'dutytable-479405',
    authDomain: 'dutytable-479405.firebaseapp.com',
    storageBucket: 'dutytable-479405.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChi09zyRm-cUUvRYsggxCUE6hxkzRf9is',
    appId: '1:174693600398:android:b0c41f8e5b126cc9758ddf',
    messagingSenderId: '174693600398',
    projectId: 'dutytable-479405',
    storageBucket: 'dutytable-479405.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeRAHBO_zLFepYR3ORj5LzRedGBcaE9HQ',
    appId: '1:174693600398:ios:e3901c8b73d0050d758ddf',
    messagingSenderId: '174693600398',
    projectId: 'dutytable-479405',
    storageBucket: 'dutytable-479405.firebasestorage.app',
    androidClientId: '174693600398-9kgf5tj9vidoc9f6791v8n1n4rl5llb8.apps.googleusercontent.com',
    iosClientId: '174693600398-kt7o6r2jne782tkfbna9g5sl9b72vdjm.apps.googleusercontent.com',
    iosBundleId: 'com.schedulelab.dutytable',
  );
}
