// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyQ011VMMFRyw8Qi2GkMlY93iXSes0eHs',
    appId: '1:362604763800:web:0c19e39f1cfcfcd3abceed',
    messagingSenderId: '362604763800',
    projectId: 'dutytable-49a2b',
    authDomain: 'dutytable-49a2b.firebaseapp.com',
    storageBucket: 'dutytable-49a2b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXa-EzFRahBGu8qz5yZ_-JXFMp-yBx3Cc',
    appId: '1:362604763800:android:431478324dbefd4babceed',
    messagingSenderId: '362604763800',
    projectId: 'dutytable-49a2b',
    storageBucket: 'dutytable-49a2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVXQStnHDjFJACtKuk2JuXMCa2EyLlQJQ',
    appId: '1:362604763800:ios:f0b452e9d0cab008abceed',
    messagingSenderId: '362604763800',
    projectId: 'dutytable-49a2b',
    storageBucket: 'dutytable-49a2b.firebasestorage.app',
    iosBundleId: 'com.schedulelab.dutytable',
  );
}
